/** @type {import('tailwindcss').Config} */

module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      sm: '550px',
      md: '834px',
      lg: '1425px',
      xl: '1920px',
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        md: '2rem',
        lg: '3rem',
        xl: '7.5rem',
      },
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: '#000000',
      white: '#FFFFFF',
      orange: {
        300: '#FBE3D9',
        400: '#FFC2A6',
        500: '#FF570A',
        600: '#C93F00',
      },
      pink: {
        300: '#F9EEF8',
        400: '#F1DCEE',
        500: '#F2B8EB',
        600: '#D372C7',
        700: '#BF62B4',
        900: '#563751',
      },
      aqua: {
        300: '#BCF3F0',
        400: '#64DDD5',
        500: '#25BAB1',
        600: '#319E98',
      },
      yellow: {
        300: '#FBF7CE',
        400: '#F5EE98',
        500: '#F0DF22',
        600: '#D4B822',
      },
      cream: {
        300: '#F6F6F1',
        400: '#EEEEE3',
        500: '#D7D7C7',
        600: '#B5B59F',
      },
      neutral: {
        0: '#FFFFFF',
        100: '#F4F4F4',
        200: '#DCDCDC',
        300: '#C5C5C5',
        400: '#A8A8A8',
        500: '#909090',
        600: '#616161',
        700: '#4A4A4A',
        800: '#363636',
        900: '#171717',
        950: '#070707',
        1000: '#000000',
      },
    },
    fontSize: {
      button: [
        '18px',
        {
          lineHeight: '24px',
          letterSpacing: '2%',
          fontWeight: '700',
        },
      ],
      subtitle: ['24px', '32px'],
      'subtitle-sm': ['20px', '24px'],
      'heading-h4': ['24px', '32px'],
      'heading-sm': ['32px', '32px'],
      'heading-sm-sm': ['28px', '32px'],
      'heading-md': ['48px', '56px'],
      'heading-md-sm': ['32px', '32px'],
      'heading-lg': ['64px', '64px'],
      'heading-lg-sm': ['40px', '48px'],
      'heading-xl': ['72px', '80px'],
      'heading-xl-sm': ['56px', '64px'],
      label: [
        '14px',
        {
          lineHeight: '20px',
          fontWeight: '700',
        },
      ],
      'body-sm': ['14px', '20px'],
      'body-sm-sm': ['14px', '20px'],
      'body-md': ['16px', '24px'],
      'body-md-sm': ['16px', '24px'],
      'body-lg': ['20px', '28px'],
      'body-lg-xs': ['18px', '24px'],
      'body-lg-sm': ['18px', '28px'],
      'body-xl': ['24px', '32px'],
      'body-xl-sm': ['20px', '28px'],
      'body-sm-sm': ['16px', '24px'],
      'body-blog': ['18px', '26px'],
    },
    fontFamily: {
      heading: ['Scandia', 'sans-serif'],
      body: ['Work Sans', 'sans-serif'],
    },
    extend: {
      spacing: {
        30: '7.5rem',
        38: '9.5rem',
      },
      boxShadow: {
        default: '0.78px 1.55px 0px 0px',
        border: '1px 2px 0px 0px',
        faq: '0px 8px 8px 0px',
        'trust-card': '16px 13px 30px 0px #F2B8EB80, -42px 3px 54px -10px #64DDD557, 10px -29px 55px -10px #FF6E2B42',
      },
      lineClamp: {
        2: '2',
        8: '8',
        9: '9',
        10: '10',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.neutral[900]'),
            '--tw-prose-headings': theme('colors.neutral[900]'),
            '--tw-prose-lead': theme('colors.neutral[900]'),
            '--tw-prose-links': theme('colors.neutral[900]'),
            '--tw-prose-bold': theme('colors.neutral[900]'),
            '--tw-prose-counters': theme('colors.neutral[900]'),
            '--tw-prose-bullets': theme('colors.neutral[900]'),
            '--tw-prose-hr': theme('colors.neutral[900]'),
            '--tw-prose-quotes': theme('colors.neutral[900]'),
            '--tw-prose-quote-borders': theme('colors.neutral[900]'),
            '--tw-prose-captions': theme('colors.neutral[900]'),
            '--tw-prose-code': theme('colors.neutral[900]'),
            '--tw-prose-pre-code': theme('colors.neutral[0]'),
            '--tw-prose-pre-bg': theme('colors.neutral[900]'),
            '--tw-prose-th-borders': theme('colors.neutral[900]'),
            '--tw-prose-td-borders': theme('colors.neutral[900]'),
            '--tw-prose-invert-body': theme('colors.neutral[0]'),
            '--tw-prose-invert-headings': theme('colors.neutral[0]'),
            '--tw-prose-invert-lead': theme('colors.neutral[0]'),
            '--tw-prose-invert-links': theme('colors.neutral[0]'),
            '--tw-prose-invert-bold': theme('colors.neutral[0]'),
            '--tw-prose-invert-counters': theme('colors.neutral[0]'),
            '--tw-prose-invert-bullets': theme('colors.neutral[0]'),
            '--tw-prose-invert-hr': theme('colors.neutral[0]'),
            '--tw-prose-invert-quotes': theme('colors.neutral[0]'),
            '--tw-prose-invert-quote-borders': theme('colors.neutral[0]'),
            '--tw-prose-invert-captions': theme('colors.neutral[0]'),
            '--tw-prose-invert-code': theme('colors.neutral[0]'),
            '--tw-prose-invert-pre-code': theme('colors.neutral[900]'),
            '--tw-prose-invert-pre-bg': theme('colors.neutral[0]'),
            '--tw-prose-invert-th-borders': theme('colors.neutral[0]'),
            '--tw-prose-invert-td-borders': theme('colors.neutral[0]'),
          },
        },
      }),
      backgroundImage: {
        'noise-pattern': 'url("/chip-with-gradient-noisy.png")',
      },
      flexBasis: {
        '1/2-gap-6': 'calc(50% - 1.5rem)',
        '1/3-gap-6': 'calc(33.3333% - 1.5rem)',
        '1/4-gap-6': 'calc(25% - 1.5rem)',
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('tailwindcss-animate')],
};
